
/*
{{.SecondName}} is a package automatically generated by ´gobi´. Happy Hacking!
*/
package {{.SecondName}}

import (
	"errors"
)

// My{{.SecondName}}Example is a example type automatically generated by ´gobi´.
type My{{.SecondName}}Example struct {
	id 	 int
	name string
}

// New creates a new *My{{.SecondName}}Example object
func New(id int, name string) (*My{{.SecondName}}Example, error) {
	if name == "" {
		return nil, errors.New("Name is empty.")
	}

	return &My{{.SecondName}}Example{id, name}, nil
}

// Id of the My{{.SecondName}}Example
func (ex My{{.SecondName}}Example) Id() int {
	return ex.id
}

// Name of the My{{.SecondName}}Example
func (ex My{{.SecondName}}Example) Name() string {
	return ex.name
}

// SetId for the My{{.SecondName}}Example
func (ex *My{{.SecondName}}Example) SetId(id int) {
	ex.id = id
}

// SetName for the My{{.SecondName}}Example
func (ex *My{{.SecondName}}Example) SetName(name string) {
	ex.name = name
}




