/*
{{.SecondName}} is a command line tool automatically generated by ´gobi´. Happy hacking!
*/
package main

import (
	"flag"
	"fmt"
)

func main() {
	var f string

	flag.StringVar(&f, "f", "gobi is awesome", "Just prints.")
	flag.Parse()

	fmt.Println(f)
}
